config/routes.rb
Labo::Application.routes.draw do
  resources :prestamo_libros

  resources :prestamo_instrumentos

  resources :personas

  resources :libros

  resources :instrumentos

end

app/models/instrumento.rb
class Instrumento < ActiveRecord::Base
  attr_accessible :instrumento_id, :detalles, :marca, :nombre, :nro_serie, :observaciones,
                  :relacionados

  validates :instrumento_id, presence: true, uniqueness: true, length: {maximum: 4, minimum:4} ,
            numericality: {only_integer: true}
  validates :nombre, presence: true, length: { maximum: 255 }
  validates :marca, length: { maximum: 255 }
  validates :nro_serie, length: { maximum: 255 }


end

app/controllers/instrumentos_controller.rb
class InstrumentosController < ApplicationController
  # GET /instrumentos
  # GET /instrumentos.json
  def index
    @instrumentos = Instrumento.order('instrumento_id').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instrumentos }
    end
  end

  # GET /instrumentos/1
  # GET /instrumentos/1.json
  def show
    @instrumento = Instrumento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instrumento }
    end
  end

  # GET /instrumentos/new
  # GET /instrumentos/new.json
  def new
    @instrumento = Instrumento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instrumento }
    end
  end

  # GET /instrumentos/1/edit
  def edit
    @instrumento = Instrumento.find(params[:id])
  end

  # POST /instrumentos
  # POST /instrumentos.json
  def create
    @instrumento = Instrumento.new(params[:instrumento])

    respond_to do |format|
      if @instrumento.save
        format.html { redirect_to @instrumento, notice: 'Instrumento creado.' }
        format.json { render json: @instrumento, status: :created, location: @instrumento }
      else
        format.html { render action: "new" }
        format.json { render json: @instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instrumentos/1
  # PUT /instrumentos/1.json
  def update
    @instrumento = Instrumento.find(params[:id])

    respond_to do |format|
      if @instrumento.update_attributes(params[:instrumento])
        format.html { redirect_to @instrumento, notice: 'Instrumento actualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instrumentos/1
  # DELETE /instrumentos/1.json
  def destroy
    @instrumento = Instrumento.find(params[:id])
    @instrumento.destroy

    respond_to do |format|
      format.html { redirect_to instrumentos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/instrumentos_helper.rb
module InstrumentosHelper
end

app/views/instrumentos/_form.html.erb
<%= form_for(@instrumento) do |f| %>
  <% if @instrumento.errors.any? %>
    <div id="error_explanation">
      <h2> Uppps, hay errores que deberás corregir:</h2>

      <ul>
      <% @instrumento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instrumento_id %><br />
    <%= f.number_field :instrumento_id %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :marca %><br />
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :nro_serie %><br />
    <%= f.text_field :nro_serie %>
  </div>
  <div class="field">
    <%= f.label :observaciones %><br />
    <%= f.text_area :observaciones, :size =>" 40x5" %>
  </div>
  <div class="field">
    <%= f.label :detalles %><br />
    <%= f.text_area :detalles, :size =>" 40x5"  %>
  </div>
  <div class="field">
    <%= f.label :relacionados %><br />
    <%= f.text_area :relacionados, :size =>" 40x5"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instrumentos/edit.html.erb
<h1>Editing instrumento</h1>

<%= render 'form' %>

<%= link_to 'Ver', @instrumento %> |
<%= link_to 'Atrás', instrumentos_path %>

app/views/instrumentos/index.html.erb
<h1>Listing instrumentos</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Marca</th>
    <th>Nro serie</th>
    <th>Observaciones</th>
    <th>Detalles</th>
    <th>Relacionados</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instrumentos.each do |instrumento| %>
  <tr>
    <td><%= instrumento.instrumento_id %></td>
    <td><%= instrumento.nombre %></td>
    <td><%= instrumento.marca %></td>
    <td><%= instrumento.nro_serie %></td>
    <td><%= truncate instrumento.observaciones, length:20 %></td>
    <td><%= truncate instrumento.detalles, length:20 %></td>
    <td><%= truncate instrumento.relacionados, length:20 %></td>
    <td><%= link_to 'Ver', instrumento %></td>
    <td><%= link_to 'Editar', edit_instrumento_path(instrumento) %></td>
    <td><%= link_to 'Eliminar', instrumento, confirm: '¿Está seguro que desea eliminar?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo', new_instrumento_path %>

app/views/instrumentos/new.html.erb
<h1>New instrumento</h1>

<%= render 'form' %>

<%= link_to 'Atrás', instrumentos_path %>

app/views/instrumentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @instrumento.instrumento_id %>
</p>

<p>
  <b>Nombre:</b>
  <%= @instrumento.nombre %>
</p>

<p>
  <b>Marca:</b>
  <%= @instrumento.marca %>
</p>

<p>
  <b>Nro serie:</b>
  <%= @instrumento.nro_serie %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @instrumento.observaciones %>
</p>

<p>
  <b>Detalles:</b>
  <%= @instrumento.detalles %>
</p>

<p>
  <b>Relacionados:</b>
  <%= @instrumento.relacionados %>
</p>


<%= link_to 'Editar', edit_instrumento_path(@instrumento) %> |
<%= link_to 'Atrás', instrumentos_path %>