config/routes.rb
Labo::Application.routes.draw do
  resources :prestamo_libros

  resources :prestamo_instrumentos

  resources :personas

  resources :libros

  resources :instrumentos

end

app/models/prestamo_libro.rb
class PrestamoLibro < ActiveRecord::Base
  attr_accessible :libro_id, :persona_id, :responsable_id
end

app/controllers/prestamo_libros_controller.rb
class PrestamoLibrosController < ApplicationController
  # GET /prestamo_libros
  # GET /prestamo_libros.json
  def index
    @prestamo_libros = PrestamoLibro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prestamo_libros }
    end
  end

  # GET /prestamo_libros/1
  # GET /prestamo_libros/1.json
  def show
    @prestamo_libro = PrestamoLibro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prestamo_libro }
    end
  end

  # GET /prestamo_libros/new
  # GET /prestamo_libros/new.json
  def new
    @prestamo_libro = PrestamoLibro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prestamo_libro }
    end
  end

  # GET /prestamo_libros/1/edit
  def edit
    @prestamo_libro = PrestamoLibro.find(params[:id])
  end

  # POST /prestamo_libros
  # POST /prestamo_libros.json
  def create
    @prestamo_libro = PrestamoLibro.new(params[:prestamo_libro])

    respond_to do |format|
      if @prestamo_libro.save
        format.html { redirect_to @prestamo_libro, notice: 'Prestamo libro was successfully created.' }
        format.json { render json: @prestamo_libro, status: :created, location: @prestamo_libro }
      else
        format.html { render action: "new" }
        format.json { render json: @prestamo_libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prestamo_libros/1
  # PUT /prestamo_libros/1.json
  def update
    @prestamo_libro = PrestamoLibro.find(params[:id])

    respond_to do |format|
      if @prestamo_libro.update_attributes(params[:prestamo_libro])
        format.html { redirect_to @prestamo_libro, notice: 'Prestamo libro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prestamo_libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestamo_libros/1
  # DELETE /prestamo_libros/1.json
  def destroy
    @prestamo_libro = PrestamoLibro.find(params[:id])
    @prestamo_libro.destroy

    respond_to do |format|
      format.html { redirect_to prestamo_libros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/prestamo_libros_helper.rb
module PrestamoLibrosHelper
end

app/views/prestamo_libros/_form.html.erb
<%= simple_form_for(@prestamo_libro) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :persona_id %>
    <%= f.input :libro_id %>
    <%= f.input :responsable_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/prestamo_libros/edit.html.erb
<h1>Editing prestamo_libro</h1>

<%= render 'form' %>

<%= link_to 'Show', @prestamo_libro %> |
<%= link_to 'Back', prestamo_libros_path %>

app/views/prestamo_libros/index.html.erb
<h1>Listing prestamo_libros</h1>

<table>
  <tr>
    <th>Persona codigo</th>
    <th>Libro codigo</th>
    <th>Responsable codigo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prestamo_libros.each do |prestamo_libro| %>
  <tr>
    <td><%= prestamo_libro.persona_id %></td>
    <td><%= prestamo_libro.libro_id %></td>
    <td><%= prestamo_libro.responsable_id %></td>
    <td><%= link_to 'Show', prestamo_libro %></td>
    <td><%= link_to 'Edit', edit_prestamo_libro_path(prestamo_libro) %></td>
    <td><%= link_to 'Destroy', prestamo_libro, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prestamo libro', new_prestamo_libro_path %>

app/views/prestamo_libros/new.html.erb
<h1>New prestamo_libro</h1>

<%= render 'form' %>

<%= link_to 'Back', prestamo_libros_path %>

app/views/prestamo_libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Persona codigo:</b>
  <%= @prestamo_libro.persona_id %>
</p>

<p>
  <b>Libro codigo:</b>
  <%= @prestamo_libro.libro_id %>
</p>

<p>
  <b>Responsable codigo:</b>
  <%= @prestamo_libro.responsable_id %>
</p>


<%= link_to 'Edit', edit_prestamo_libro_path(@prestamo_libro) %> |
<%= link_to 'Back', prestamo_libros_path %>