config/routes.rb
Labo::Application.routes.draw do
  resources :prestamo_libros

  resources :prestamo_instrumentos

  resources :personas

  resources :libros

  resources :instrumentos

end

app/models/libro.rb
class Libro < ActiveRecord::Base
  attr_accessible :autor, :libro_id, :editorial, :nombre, :observaciones, :ubicacion
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @libros }
    end
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
    @libro = Libro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @libro }
    end
  end

  # GET /libros/new
  # GET /libros/new.json
  def new
    @libro = Libro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @libro }
    end
  end

  # GET /libros/1/edit
  def edit
    @libro = Libro.find(params[:id])
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(params[:libro])

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render json: @libro, status: :created, location: @libro }
      else
        format.html { render action: "new" }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /libros/1
  # PUT /libros/1.json
  def update
    @libro = Libro.find(params[:id])

    respond_to do |format|
      if @libro.update_attributes(params[:libro])
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro = Libro.find(params[:id])
    @libro.destroy

    respond_to do |format|
      format.html { redirect_to libros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_form.html.erb
<%= form_for(@libro) do |f| %>
  <% if @libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% @libro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :libro_id %><br />
    <%= f.text_field :libro_id %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :editorial %><br />
    <%= f.text_field :editorial %>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br />
    <%= f.text_field :ubicacion %>
  </div>
  <div class="field">
    <%= f.label :observaciones %><br />
    <%= f.text_area :observaciones %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editing libro</h1>

<%= render 'form' %>

<%= link_to 'Ver', @libro %> |
<%= link_to 'Atrás', libros_path %>

app/views/libros/index.html.erb
<h1>Listing libros</h1>

<table>
  <tr>
    <th>Cod</th>
    <th>Nombre</th>
    <th>Autor</th>
    <th>Editorial</th>
    <th>Ubicacion</th>
    <th>Observaciones</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @libros.each do |libro| %>
  <tr>
    <td><%= libro.libro_id%></td>
    <td><%= libro.nombre %></td>
    <td><%= libro.autor %></td>
    <td><%= libro.editorial %></td>
    <td><%= libro.ubicacion %></td>
    <td><%= libro.observaciones %></td>
    <td><%= link_to 'Show', libro %></td>
    <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
    <td><%= link_to 'Destroy', libro, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Libro', new_libro_path %>

app/views/libros/new.html.erb
<h1>New libro</h1>

<%= render 'form' %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cod:</b>
  <%= @libro.libro_id %>
</p>

<p>
  <b>Nombre:</b>
  <%= @libro.nombre %>
</p>

<p>
  <b>Autor:</b>
  <%= @libro.autor %>
</p>

<p>
  <b>Editorial:</b>
  <%= @libro.editorial %>
</p>

<p>
  <b>Ubicacion:</b>
  <%= @libro.ubicacion %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @libro.observaciones %>
</p>


<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>