config/routes.rb
Labo::Application.routes.draw do
  resources :prestamo_libros

  resources :prestamo_instrumentos

  resources :personas

  resources :libros

  resources :instrumentos

end

app/models/prestamo_instrumento.rb
class PrestamoInstrumento < ActiveRecord::Base

  attr_accessible :instrumento_id, :persona_id, :responsable_id

  belongs_to :persona
end

app/controllers/prestamo_instrumentos_controller.rb
class PrestamoInstrumentosController < ApplicationController
  # GET /prestamo_instrumentos
  # GET /prestamo_instrumentos.json
  def index
    @prestamo_instrumentos = PrestamoInstrumento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prestamo_instrumentos }
    end
  end

  # GET /prestamo_instrumentos/1
  # GET /prestamo_instrumentos/1.json
  def show
    @prestamo_instrumento = PrestamoInstrumento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prestamo_instrumento }
    end
  end

  # GET /prestamo_instrumentos/new
  # GET /prestamo_instrumentos/new.json
  def new
    @prestamo_instrumento = PrestamoInstrumento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prestamo_instrumento }
    end
  end

  # GET /prestamo_instrumentos/1/edit
  def edit
    @prestamo_instrumento = PrestamoInstrumento.find(params[:id])
  end

  # POST /prestamo_instrumentos
  # POST /prestamo_instrumentos.json
  def create
    @prestamo_instrumento = PrestamoInstrumento.new(params[:prestamo_instrumento])

    respond_to do |format|
      if @prestamo_instrumento.save
        format.html { redirect_to @prestamo_instrumento, notice: 'Prestamo instrumento was successfully created.' }
        format.json { render json: @prestamo_instrumento, status: :created, location: @prestamo_instrumento }
      else
        format.html { render action: "new" }
        format.json { render json: @prestamo_instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prestamo_instrumentos/1
  # PUT /prestamo_instrumentos/1.json
  def update
    @prestamo_instrumento = PrestamoInstrumento.find(params[:id])

    respond_to do |format|
      if @prestamo_instrumento.update_attributes(params[:prestamo_instrumento])
        format.html { redirect_to @prestamo_instrumento, notice: 'Prestamo instrumento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prestamo_instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestamo_instrumentos/1
  # DELETE /prestamo_instrumentos/1.json
  def destroy
    @prestamo_instrumento = PrestamoInstrumento.find(params[:id])
    @prestamo_instrumento.destroy

    respond_to do |format|
      format.html { redirect_to prestamo_instrumentos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/prestamo_instrumentos_helper.rb
module PrestamoInstrumentosHelper
end

app/views/prestamo_instrumentos/_form.html.erb
<%= simple_form_for(@prestamo_instrumento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :persona_id %>
    <%= f.input :instrumento_id %>
    <%= f.input :responsable_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/prestamo_instrumentos/edit.html.erb
<h1>Editing prestamo_instrumento</h1>

<%= render 'form' %>

<%= link_to 'Show', @prestamo_instrumento %> |
<%= link_to 'Back', prestamo_instrumentos_path %>

app/views/prestamo_instrumentos/index.html.erb
<h1>Listing prestamo_instrumentos</h1>

<table>
  <tr>
    <th>Persona codigo</th>
    <th>Instrumento codigo</th>
    <th>Responsable codigo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prestamo_instrumentos.each do |prestamo_instrumento| %>
  <tr>
    <td><%= prestamo_instrumento.persona_id %></td>
    <td><%= prestamo_instrumento.instrumento_id %></td>
    <td><%= prestamo_instrumento.responsable_id %></td>
    <td><%= link_to 'Show', prestamo_instrumento %></td>
    <td><%= link_to 'Edit', edit_prestamo_instrumento_path(prestamo_instrumento) %></td>
    <td><%= link_to 'Destroy', prestamo_instrumento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>


<br />

<%= link_to 'New Prestamo instrumento', new_prestamo_instrumento_path %>

app/views/prestamo_instrumentos/new.html.erb
<h1>New prestamo_instrumento</h1>

<%= render 'form' %>

<%= link_to 'Back', prestamo_instrumentos_path %>

app/views/prestamo_instrumentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Persona codigo:</b>
  <%= @prestamo_instrumento.persona_id %>
</p>

<p>
  <b>Instrumento codigo:</b>
  <%= @prestamo_instrumento.instrumento_id %>
</p>

<p>
  <b>Responsable codigo:</b>
  <%= @prestamo_instrumento.responsable_id %>
</p>


<%= link_to 'Edit', edit_prestamo_instrumento_path(@prestamo_instrumento) %> |
<%= link_to 'Back', prestamo_instrumentos_path %>